# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servos.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cservos.proto\"$\n\x0cUpdateServos\x12\x14\n\x0cservo_values\x18\x01 \x03(\x05\"\x1e\n\x0f\x41\x63kUpdateServos\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32>\n\x10SendUpdateSerovs\x12*\n\x05Start\x12\r.UpdateServos\x1a\x10.AckUpdateServos\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servos_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATESERVOS._serialized_start=16
  _UPDATESERVOS._serialized_end=52
  _ACKUPDATESERVOS._serialized_start=54
  _ACKUPDATESERVOS._serialized_end=84
  _SENDUPDATESEROVS._serialized_start=86
  _SENDUPDATESEROVS._serialized_end=148
# @@protoc_insertion_point(module_scope)
